version: '3'

services:
  db:
    container_name: kurteyki-mariadb
    hostname: mariadb
    image: mariadb
    environment:
      MYSQL_DATABASE: kurteyki
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database:/var/lib/mysql
      - ./kurteyki.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - default
    
  phpmyadmin:
    container_name: kurteyki-pma
    image: phpmyadmin/phpmyadmin
    hostname: pma
    ports:
      - 8000:80
    environment:
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root

  app:
    container_name: kurteyki-app
    image: kurteyki-lms
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/var/www/html
    networks:
      - default